[package]
name = "aqua"
version = "0.1.0"
authors = ["Robby Madruga <robbymadruga@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.0"
regex = "0.2.0"
llvm-sys = "70"

[build-dependencies]
lalrpop = "0.16.0"