[package]
name = "aqua"
version = "0.1.0"
authors = ["Robby Madruga <robbymadruga@gmail.com>"]
build = "build.rs"

[dependencies]
structopt = "0.3.2"
lalrpop-util = "0.17.2"
regex = "1.3.1"
cranelift = "0.42.0"
codespan = "0.4.1"

[build-dependencies]
lalrpop = "0.17.2"